galaxy_info:
  author: Tim Oliver Rabl
  description:  dotfiles bootstrap

  license: MIT

  min_ansible_version: 2.10

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: macOS
      versions:
        - all

  galaxy_tags:
    - dotfiles

dependencies: []