---
# tasks file for systemd_networkd
- name: Check for existing ifupdown interfaces file
  tags:
    - systemd_networkd
  become: true
  register: ifupdown
  stat:
    path: "{{ ifupdown_path }}/interfaces"

- name: Remove ifupdown interfaces file
  tags:
    - systemd_networkd
  become: true
  when: ifupdown.stat.exists
  file:
    path: "{{ ifupdown_path }}/interfaces"
    state: absent

- name: Render systemd_networkd link files
  become: true
  tags:
    - systemd_networkd
  template:
    src: networkd_link.j2
    dest: "{{ networkd_path }}/{{ item.key }}.link"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
  when: item.value.link is defined
  loop: "{{ networkd.interfaces | dict2items }}"
  notify:
    - Restart systemd_networkd

- name: Render systemd_networkd netdev files
  become: true
  tags:
    - systemd_networkd
  template:
    src: networkd_netdev.j2
    dest: "{{ networkd_path }}/{{ item.key }}.netdev"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
  when: item.value.netdev is defined
  loop: "{{ networkd.interfaces | dict2items }}"
  notify:
    - Restart systemd_networkd

- name: Render systemd_networkd network files
  become: true
  tags:
    - systemd_networkd
  template:
    src: networkd_network.j2
    dest: "{{ networkd_path }}/{{ item.key }}.network"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
  when: item.value.network is defined
  loop: "{{ networkd.interfaces | dict2items }}"
  notify:
    - Restart systemd_networkd

- name: Flush restart handlers
  meta: flush_handlers