---
- name: Bootstrapping
  hosts: all
  become: False

  vars:
    group: >-
      {% if ansible_distribution | lower == "macosx" %}staff{% else %}
      {{ ansible_ssh_user }}{% endif %}

  tasks:
    - name: Include host specific vars file
      include_vars: 
        dir: host_vars/
        files_matching: "{{ ansible_hostname }}.yaml"

    - name: Import dotfiles bootstrapping
      import_role:
        name: dotfiles

    - name: Import brew role
      when: ansible_distribution | lower == 'macosx'
      import_role:
        name: brew

    - name: Import vim role
      import_role:
        name: vim
    
    - name: Import vscode role
      import_role:
        name: vscode
