---
# tasks file for dotfiles
- name: Assert variables
  tags:
    - check_vars
  assert:
    quiet: True
    that:
      - dotfiles.url is defined
      - dotfiles.branch is defined

- name: Clone dotfiles
  tags:
    - dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: "{{ destination }}"
    version: "{{ dotfiles.branch }}"
    accept_hostkey: True
    
- name: Synchronize dotfiles with home folder
  tags:
    - dotfiles
  synchronize:
    src: >-
      {{ destination }}/{% if dotfiles.options.os_specific %}{{ ansible_distribution | lower }}/{% endif %}{% if dotfiles.options.version_specific %}{{ ansible_distribution_version | lower }}/{% endif %}
    dest: "{{ lookup('env', 'HOME') }}/"
