---
- name: Check required vars
  tags:
    - check_vars
  assert:
    quiet: true
    that:
      - dotfiles.url
      - dotfiles.destination

- name: Clone dotfiles repositories
  tags:
    - dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: "{{ dotfiles.destination }}"
    version: "{{ dotfiles.branch | default('main') }}"
    accept_hostkey: True

- name: Copy dotfiles to home folder
  tags:
    - dotfiles
  synchronize:
    src: "{{ dotfiles.destination }}/"
    dest: "{{ lookup('env', 'HOME') }}/"
  when:
    - not dotfiles.options.os_specific
    - not dotfiles.options.version_specific

- name: Copy OS specific dotfiles to home folder
  tags:
    - dotfiles
  synchronize:
    src: "{{ dotfiles.destination }}/{{ ansible_distribution | lower }}/"
    dest: "{{ lookup('env', 'HOME') }}/"
  when:
    - dotfiles.options.os_specific
    - not dotfiles.options.version_specific

- name: Copy OS / version specific dotfiles to home folder
  tags:
    - dotfiles
  synchronize:
    src: "{{ dotfiles.destination }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_version | lower }}/"
    dest: "{{ lookup('env', 'HOME') }}/"
  when:
    - dotfiles.options.os_specific
    - dotfiles.options.version_specific
