---
# tasks file for vscode
- name: Get installed vscode extensions
  register: extensions
  tags:
    - vscode
  command: "code --list-extensions"
  changed_when: False

- name: Install vscode extensions
  tags:
    - vscode
  when:
    - item.name not in extensions.stdout_lines
  command: |
    code {% if item.state is defined and item.state == "absent" %}--remove-extensions
    {% else %}--install-extension
    {% endif %} {{ item.name }}
  loop: "{{ vscode.extensions }}"

- name: Ensure vscode settings
  tags:
    - vscode
  copy:
    src: "{{ vscode.settings.source }}"
    dest: "{{ destination }}"
    remote_src: True