---
- name: Get installed vscode extensions
  register: installed
  tags:
    - vscode
  command: "code --list-extensions"

- name: Install vscode extensions
  tags:
    - vscode
  when:
    - vscode.extensions is defined
    - item.name not in installed.stdout_lines
  command: "code {% if item.state is defined and item.state == 'absent' %}--remove-extensions{% else %}--install-extension{% endif %} {{ item.name }}"
  loop: "{{ vscode.extensions }}"

- name: Install vscode settings
  ignore_errors: True
  tags:
    - vscode
  copy:
    src: "{{ lookup('env', 'HOME' ) }}/vscode.settings"
    dest: "{{ home }}{{ settings.destination.dir }}{{ settings.destination.filename }}"
    remote_src: True