---
# tasks file for systemd-resolved
- name: Ensure resolved.conf.d folder
  tags:
    - systemd-resolved
  become: true
  file:
    path: "{{ resolved.confd.path | default(confd.path) }}"
    state: directory
    owner: "{{ resolved.confd.owner | default(dir.owner) }}"
    group: "{{ resolved.confd.group | default(dir.group) }}"
    mode: "{{ resolved.confd.mode | default(dir.mode) }}"

- name: Debug
  tags:
    - debug
  debug:
    msg: "{{ ansible_hostname }}"

- name: Render resolved configuration files
  tags:
    - systemd-resolved
  become: true
  template:
    src: ../templates/resolved.j2
    dest: "{{ resolved.confd.path | default(confd.path) }}/{{ item.key }}.conf"
    owner: "{{ item.value.owner | default(file.owner) }}"
    group: "{{ item.value.group | default(file.group) }}"
    mode: "{{ item.value.mode | default(file.mode) }}"
  when: item.value.resolve is defined
  loop: "{{ resolved.configs | dict2items }}"
  notify:
    - Restart systemd-resolved