---
# tasks file for brew
- name: Check for existing homebrew installation
  tags:
    - brew
  register: stat
  changed_when: false
  stat:
    path: "{{ brew.location | default(install_location) }}"

- name: Install homebrew
  tags:
    - brew
  when: not stat
  debug:
    msg: ""
  notify: Install homebrew

- name: Updating homebrew
  tags:
    - brew
  homebrew:
    update_homebrew: True

- name: Upgrade all homebrew packages
  tags:
    - brew
  homebrew:
    upgrade_all: True

- name: Register installed formulae
  tags:
    - brew
  register: formulae
  shell: "{{ list_formulae }}"
  changed_when: False

- name: Register installed casks
  tags:
    - brew
  register: casks
  shell: "{{ list_casks }}"
  changed_when: False

- name: Processing formulae
  tags:
    - brew
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  when:
    - item.name not in formulae.stdout_lines
  loop: "{{ brew.formulae }}"

- name: Processing casks
  tags:
    - brew
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    accept_external_apps: True
    install_options: "app_dir={{ brew.casks_app_dir | default(casks_app_dir) }}"
  when:
    - item.name not in casks.stdout_lines
  loop: "{{ brew.casks }}"