---
- name: Check for brew
  tags:
    - brew
  register: stat
  changed_when: false
  stat:
    path: "{{ brew.location | default('/usr/local/bin/brew') }}"

- name: Install homebrew
  tags:
    - brew
  when: not stat
  shell: brew.cmd

- name: Updating homebrew
  tags:
    - brew
  homebrew:
    update_homebrew: True

- name: Upgrade all homebrew packages
  tags:
    - brew
  homebrew:
    upgrade_all: True

- name: Register installed formulae
  tags:
    - brew
  register: installed_formulae
  shell: "brew list --formulae | sed 's/\t/\r/g'"
  changed_when: False

- name: Register installed casks
  tags:
    - brew
  register: installed_casks
  shell: "brew list --casks | sed 's/\t/\r/g'"
  changed_when: False

- name: Processing formulae
  tags:
    - brew
  homebrew:
    name: "{{ item.name }}"
    state: "{% if item.state is defined %}item.state{% else %}present{% endif %}"
  when: item.name not in installed_formulae.stdout_lines
  loop: "{{ brew.formulae }}"

- name: Processing casks
  tags:
    - brew
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{% if item.state is defined %}item.state{% else %}absent{% endif %}"
    accept_external_apps: True
    install_options: "app_dir={{ brew.app_dir | default(lookup('env', 'HOME') + '/Applications') }}"
  when: item.name not in installed_casks.stdout_lines
  loop: "{{ brew.casks }}"
