---
driver:
  name: delegated

lint: |
  set -e 
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: docker-vscode-1
    image: centos:8
    pre_build_image: True

provisioner:
  name: ansible

verifier:
  name: ansible
  enabled: True
