---
# tasks file for vim
- name: Ensure vim folders
  tags:
    - vim
  file:
    path: "{{ lookup('env', 'HOME') }}/{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(ansible_ssh_user) }}"
    group: "{{ item.group | default(group) }}"
    mode: "{{ item.mode | default(0750) }}"
  loop: "{{ vim.folders }}"

- name: Install vim autoload configs
  tags:
    - vim
  get_url:
    url: "{{ item.url }}"
    dest: "{{ lookup('env', 'HOME' ) }}/{{ item.dest }}"
    owner: "{{ item.owner | default(ansible_ssh_user) }}"
    group: "{{ item.group | default(group) }}"
    mode: "{{ item.mode | default(0640) }}"
  loop: "{{ vim.autoload }}"
  notify:
    - Install plugins