name: Ansible Lint  # feel free to pick your own name

on:
  push:
    branches:
      - main*
      - master*
  pull_request:
    branches:
      - main*
      - master*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible playboooks, tasks and roles
      uses: ansible/ansible-lint-action@v4.1.0
      with:
        targets: |
          **/*.yaml
          **/*.yml
        override-deps: |
          ansible==2.10.3
          ansible-lint==4.3.7
